/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  IsEnum,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";

import { Type } from "class-transformer";
import { EnumEventCategories } from "./EnumEventCategories";
import { RecommendationUpdateManyWithoutEventsInput } from "./RecommendationUpdateManyWithoutEventsInput";

@InputType()
class EventUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  date?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumEventCategories,
    isArray: true,
  })
  @IsEnum(EnumEventCategories, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumEventCategories], {
    nullable: true,
  })
  categories?: Array<"Option1">;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  popularity?: number | null;

  @ApiProperty({
    required: false,
    type: () => RecommendationUpdateManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => RecommendationUpdateManyWithoutEventsInput)
  @IsOptional()
  @Field(() => RecommendationUpdateManyWithoutEventsInput, {
    nullable: true,
  })
  recommendations?: RecommendationUpdateManyWithoutEventsInput;
}

export { EventUpdateInput as EventUpdateInput };
